language: rust
rust:
  - stable
cache: cargo
env:
  # Limit number of samples so build doesn't take forever
  - SAMPLES=2
jobs:
  include:
    - stage: build
      script:
        - cargo build --verbose --release --all --examples
        - cargo test --verbose --release --all
        - cargo build --verbose --release --all --examples --features render_bounding_volumes
        - cargo build --verbose --release --all --examples --features flat_scene
        - cargo build --verbose --release --all --examples --features kdtree
    - stage: run
      script: source ./run-all-examples.sh
    - stage: render_bounding_volumes
      script: source ./run-all-examples.sh --features render_bounding_volumes
    - stage: flat_scene
      script: source ./run-all-examples.sh --features flat_scene
    - stage: kdtree
      script: source ./run-all-examples.sh --features kdtree
