language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --verbose --release --all --examples
  - cargo test --verbose --release --all
  - cargo build --verbose --release --all --examples --features render_bounding_volumes
  - cargo build --verbose --release --all --examples --features flat_scene
  - cargo build --verbose --release --all --examples --features kdtree
  - source ./run-all-examples.sh
  - source ./run-all-examples.sh --features render_bounding_volumes
  - source ./run-all-examples.sh --features flat_scene
  - ./run-all-examples.sh --features kdtree
